recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: openai-gpt-4

policies:
- name: FlowPolicy
- name: IntentlessPolicy
assistant_id: 20250207-124835-wood-swale
